SELECT * FROM customers_data LIMIT 20;

--Total revenue generated by male vs female 

SELECT gender,SUM(purchase_amount) AS revenue
FROM customers_data
GROUP BY gender;

-- customers who used a discount but still spent more than the average purchase amount

SELECT customer_id,purchase_amount
FROM customers_data
WHERE purchase_amount >=(SELECT AVG(purchase_amount) FROM customers_data) 
AND discount_applied='Yes';

-- Top 5 products with the highest average review rating

SELECT item_purchased , ROUND(AVG(review_rating :: numeric),2) AS average_review_rating 
FROM customers_data
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- Comparing the average Purchase Amounts between Standard and Express Shipping. 

SELECT shipping_type,ROUND(AVG(purchase_amount),2)
FROM customers_data
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;

-- Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.

SELECT subscription_status,
COUNT(customer_id) AS total_customers,
SUM(purchase_amount) AS total_revenue,
ROUND(AVG(purchase_amount),2) AS avg_spend
FROM customers_data

GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC;

--Which 5 products have the highest percentage of purchases with discounts applied?

SELECT item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied='Yes' THEN 1 ELSE 0 END)/COUNT(*),1) AS discount_rate
FROM customers_data
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

--Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

WITH customer_type_cte as(
SELECT customer_id , previous_purchases,
 CASE WHEN previous_purchases = 1 THEN 'New'
 	  WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	   ELSE 'LOYAL'
	   END AS customer_segment
FROM customers_data
)
SELECT customer_segment,COUNT(*) AS number_of_customers FROM customer_type_cte
GROUP BY customer_segment ;

--What are the top 3 most purchased products within each category

WITH item_counts AS(
SELECT category, item_purchased,
COUNT(customer_id) AS total_orders,
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
FROM customers_data 
GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;

--Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status, 
COUNT(customer_id) AS repeate_buyers
FROM customers_data
WHERE previous_purchases >5
GROUP BY subscription_status;

-- What is the revenue contribution of each age group? 

SELECT age_group,
SUM(purchase_amount) AS total_revenue
FROM customers_data
GROUP BY age_group
ORDER BY total_revenue DESC;